# Parser lexing package. Generated by CongoCC Parser Generator. Do not edit.

import bisect
from enum import Enum, auto, unique
import logging
import re

# from .tokens import (TokenType, LexicalState, InvalidToken, IgnoredToken,
#                      SkippedToken, new_token)

from .tokens import *

from .utils import as_chr, _List, EMPTY_SET, HashSet, HashMap

# See if an accelerated BitSet is available.
try:
    from _bitset import BitSet
    _fast_bitset = True
except ImportError:
    from .utils import BitSet
    _fast_bitset = False




logger = logging.getLogger(__name__)

DEFAULT_TAB_SIZE = 1

#
# Hack to allow token types to be referenced in snippets without
# qualifying
#
globals().update(TokenType.__members__)

# NFA code and data

# The nitty-gritty of the NFA code follows

def NfaIndex0(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '"':
        if valid_types is None or STRING_LITERAL_DQ in valid_types:
            next_states.set(25)
    elif ch == '\'':
        if valid_types is None or STRING_LITERAL_SQ in valid_types:
            next_states.set(26)
    elif ch == '-':
        if valid_types is None or INTEGER_LITERAL in valid_types:
            next_states.set(8)
        if valid_types is None or FLOATING_POINT_LITERAL in valid_types:
            next_states.set(39)
        if valid_types is None or INVALID_HEX_INTEGER in valid_types:
            next_states.set(47)
        if valid_types is None or INVALID_LEADING_ZERO_INTEGER in valid_types:
            next_states.set(48)
    elif ch == '.':
        if valid_types is None or FLOATING_POINT_LITERAL in valid_types:
            next_states.set(15)
    elif ch == '/':
        if valid_types is None or COMMENT_MULTI_LINE in valid_types:
            next_states.set(33)
        if valid_types is None or COMMENT_SINGLE_LINE in valid_types:
            next_states.set(30)
    elif ch == '0':
        if valid_types is None or INVALID_LEADING_ZERO_INTEGER in valid_types:
            next_states.set(6)
        if valid_types is None or INTEGER_LITERAL in valid_types:
            next_states.set(38)
        if valid_types is None or INVALID_HEX_INTEGER in valid_types:
            next_states.set(27)
    if ch >= '0' and ch <= '9':
        if valid_types is None or FLOATING_POINT_LITERAL in valid_types:
            next_states.set(36)
        if valid_types is None or FLOATING_POINT_LITERAL in valid_types:
            next_states.set(20)
        if valid_types is None or FLOATING_POINT_LITERAL in valid_types:
            next_states.set(13)
    elif (ch == ',') or (ch == ';'):
        if valid_types is None or ANY_SEPARATOR in valid_types:
            type = ANY_SEPARATOR
    elif check_intervals(NFA_MOVES_64, ch):
        if valid_types is None or ANY_OPERATOR in valid_types:
            next_states.set(32)
            type = ANY_OPERATOR
    if (ch == '$') or ((ch == '.') or ((ch >= '0' and ch <= '9') or ((ch >= 'A' and ch <= 'Z') or ((ch == '_') or (ch >= 'a' and ch <= 'z'))))):
        if valid_types is None or ANY_LITERAL in valid_types:
            next_states.set(29)
            type = ANY_LITERAL
    if ch == '0':
        if valid_types is None or INTEGER_LITERAL in valid_types:
            next_states.set(12)
            type = INTEGER_LITERAL
    elif ch >= '1' and ch <= '9':
        if valid_types is None or INTEGER_LITERAL in valid_types:
            next_states.set(9)
            type = INTEGER_LITERAL
    elif ch == '\t':
        if valid_types is None or WHITE_SPACE in valid_types:
            next_states.set(1)
            type = WHITE_SPACE
    elif ch == '\n':
        if valid_types is None or WHITE_SPACE in valid_types:
            next_states.set(1)
            type = WHITE_SPACE
    elif ch == '\f':
        if valid_types is None or WHITE_SPACE in valid_types:
            next_states.set(1)
            type = WHITE_SPACE
    elif ch == '\r':
        if valid_types is None or WHITE_SPACE in valid_types:
            next_states.set(1)
            type = WHITE_SPACE
    elif ch == ' ':
        if valid_types is None or WHITE_SPACE in valid_types:
            next_states.set(1)
            type = WHITE_SPACE
    elif ch == ')':
        if valid_types is None or RIGHT_PAREN in valid_types:
            type = RIGHT_PAREN
    elif ch == '(':
        if valid_types is None or LEFT_PAREN in valid_types:
            type = LEFT_PAREN
    return type

def NfaIndex1(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '\t':
        next_states.set(1)
        type = WHITE_SPACE
    elif ch == '\n':
        next_states.set(1)
        type = WHITE_SPACE
    elif ch == '\f':
        next_states.set(1)
        type = WHITE_SPACE
    elif ch == '\r':
        next_states.set(1)
        type = WHITE_SPACE
    elif ch == ' ':
        next_states.set(1)
        type = WHITE_SPACE
    return type

def NfaIndex2(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch <= ')') or ((ch >= '+' and ch <= '.') or (ch >= '0')):
        next_states.set(35)
    elif ch == '*':
        next_states.set(2)
    elif ch == '/':
        type = COMMENT_MULTI_LINE
    return type

def NfaIndex3(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch == '+') or (ch == '-'):
        next_states.set(5)
    elif ch >= '0' and ch <= '9':
        next_states.set(4)
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex4(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(4)
        type = FLOATING_POINT_LITERAL
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex5(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(4)
        return FLOATING_POINT_LITERAL
    # return None

def NfaIndex6(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(7)
        return INVALID_LEADING_ZERO_INTEGER
    # return None

def NfaIndex7(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(7)
        type = INVALID_LEADING_ZERO_INTEGER
    elif (ch == 'L') or (ch == 'l'):
        type = INVALID_LEADING_ZERO_INTEGER
    return type

def NfaIndex8(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '0':
        next_states.set(38)
        next_states.set(12)
        type = INTEGER_LITERAL
    elif ch >= '1' and ch <= '9':
        next_states.set(9)
        type = INTEGER_LITERAL
    return type

def NfaIndex9(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(9)
        type = INTEGER_LITERAL
    elif (ch == 'L') or (ch == 'l'):
        type = INTEGER_LITERAL
    return type

def NfaIndex10(ch, next_states, valid_yypes, already_matched_types):
    if (ch >= '0' and ch <= '9') or ((ch >= 'A' and ch <= 'F') or (ch >= 'a' and ch <= 'f')):
        next_states.set(11)
        return INTEGER_LITERAL
    # return None

def NfaIndex11(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch >= '0' and ch <= '9') or ((ch >= 'A' and ch <= 'F') or (ch >= 'a' and ch <= 'f')):
        next_states.set(11)
        type = INTEGER_LITERAL
    elif (ch == 'L') or (ch == 'l'):
        type = INTEGER_LITERAL
    return type

def NfaIndex12(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'L') or (ch == 'l'):
        return INTEGER_LITERAL
    # return None

def NfaIndex13(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '-':
        next_states.set(42)
    elif ch >= '0' and ch <= '9':
        next_states.set(13)
    elif (ch == 'E') or (ch == 'e'):
        next_states.set(40)
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex14(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(14)
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex15(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(16)
        return FLOATING_POINT_LITERAL
    # return None

def NfaIndex16(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '-':
        next_states.set(43)
    elif (ch == 'E') or (ch == 'e'):
        next_states.set(17)
    elif ch >= '0' and ch <= '9':
        next_states.set(16)
        type = FLOATING_POINT_LITERAL
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex17(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch == '+') or (ch == '-'):
        next_states.set(18)
    elif ch >= '0' and ch <= '9':
        next_states.set(19)
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex18(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(19)
        return FLOATING_POINT_LITERAL
    # return None

def NfaIndex19(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(19)
        type = FLOATING_POINT_LITERAL
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex20(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(20)
    elif ch == '.':
        next_states.set(21)
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex21(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch == '-':
        next_states.set(44)
    elif (ch == 'E') or (ch == 'e'):
        next_states.set(22)
    elif ch >= '0' and ch <= '9':
        next_states.set(21)
        type = FLOATING_POINT_LITERAL
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex22(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch == '+') or (ch == '-'):
        next_states.set(24)
    elif ch >= '0' and ch <= '9':
        next_states.set(23)
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex23(ch, next_states, valid_types, already_matched_types):
    type = None
    if ch >= '0' and ch <= '9':
        next_states.set(23)
        type = FLOATING_POINT_LITERAL
    elif (ch == 'D') or ((ch == 'F') or ((ch == 'd') or (ch == 'f'))):
        type = FLOATING_POINT_LITERAL
    return type

def NfaIndex24(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(23)
        return FLOATING_POINT_LITERAL
    # return None

def NfaIndex25(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch <= '!') or ((ch >= '#' and ch <= '[') or (ch >= ']')):
        next_states.set(25)
    elif ch == '\\':
        next_states.set(45)
    elif ch == '"':
        type = STRING_LITERAL_DQ
    return type

def NfaIndex26(ch, next_states, valid_types, already_matched_types):
    type = None
    if (ch <= '&') or ((ch >= '(' and ch <= '[') or (ch >= ']')):
        next_states.set(26)
    elif ch == '\\':
        next_states.set(46)
    elif ch == '\'':
        type = STRING_LITERAL_SQ
    return type

def NfaIndex27(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'X') or (ch == 'x'):
        next_states.set(28)
        return INVALID_HEX_INTEGER
    # return None

def NfaIndex28(ch, next_states, valid_yypes, already_matched_types):
    if (ch == '.') or ((ch >= '0' and ch <= '9') or ((ch >= 'A' and ch <= 'Z') or ((ch == '_') or (ch >= 'a' and ch <= 'z')))):
        next_states.set(28)
        return INVALID_HEX_INTEGER
    # return None

def NfaIndex29(ch, next_states, valid_yypes, already_matched_types):
    if (ch == '$') or ((ch == '.') or ((ch >= '0' and ch <= '9') or ((ch >= 'A' and ch <= 'Z') or ((ch == '_') or (ch >= 'a' and ch <= 'z'))))):
        next_states.set(29)
        return ANY_LITERAL
    # return None

def NfaIndex30(ch, next_states, valid_yypes, already_matched_types):
    if ch == '/':
        next_states.set(31)
        return COMMENT_SINGLE_LINE
    # return None

def NfaIndex31(ch, next_states, valid_yypes, already_matched_types):
    if (ch <= '\t') or ((ch == as_chr(0xb) or ch == '\f') or (ch >= as_chr(0xe))):
        next_states.set(31)
        return COMMENT_SINGLE_LINE
    # return None

def NfaIndex32(ch, next_states, valid_yypes, already_matched_types):
    if check_intervals(NFA_MOVES_64, ch):
        next_states.set(32)
        return ANY_OPERATOR
    # return None

def NfaIndex33(ch, next_states, valid_yypes, already_matched_types):
    if ch == '*':
        next_states.set(34)
    # return None

def NfaIndex34(ch, next_states, valid_types, already_matched_types):
    if (ch <= ')') or (ch >= '+'):
        next_states.set(34)
    elif ch == '*':
        next_states.set(2)
    # return None

def NfaIndex35(ch, next_states, valid_types, already_matched_types):
    if (ch <= ')') or (ch >= '+'):
        next_states.set(35)
    elif ch == '*':
        next_states.set(2)
    # return None

def NfaIndex36(ch, next_states, valid_types, already_matched_types):
    if ch == '-':
        next_states.set(37)
    elif ch >= '0' and ch <= '9':
        next_states.set(36)
    elif (ch == 'E') or (ch == 'e'):
        next_states.set(3)
    # return None

def NfaIndex37(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'E') or (ch == 'e'):
        next_states.set(3)
    # return None

def NfaIndex38(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'X') or (ch == 'x'):
        next_states.set(10)
    # return None

def NfaIndex39(ch, next_states, valid_types, already_matched_types):
    if ch == '.':
        next_states.set(15)
    elif ch >= '0' and ch <= '9':
        next_states.set(13)
        next_states.set(20)
        next_states.set(36)
    # return None

def NfaIndex40(ch, next_states, valid_types, already_matched_types):
    if (ch == '+') or (ch == '-'):
        next_states.set(41)
    elif ch >= '0' and ch <= '9':
        next_states.set(14)
    # return None

def NfaIndex41(ch, next_states, valid_yypes, already_matched_types):
    if ch >= '0' and ch <= '9':
        next_states.set(14)
    # return None

def NfaIndex42(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'E') or (ch == 'e'):
        next_states.set(40)
    # return None

def NfaIndex43(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'E') or (ch == 'e'):
        next_states.set(17)
    # return None

def NfaIndex44(ch, next_states, valid_yypes, already_matched_types):
    if (ch == 'E') or (ch == 'e'):
        next_states.set(22)
    # return None

def NfaIndex45(ch, next_states, valid_yypes, already_matched_types):
    if ch <= as_chr(0x10ffff):
        next_states.set(25)
    # return None

def NfaIndex46(ch, next_states, valid_yypes, already_matched_types):
    if ch <= as_chr(0x10ffff):
        next_states.set(26)
    # return None

def NfaIndex47(ch, next_states, valid_yypes, already_matched_types):
    if ch == '0':
        next_states.set(27)
    # return None

def NfaIndex48(ch, next_states, valid_yypes, already_matched_types):
    if ch == '0':
        next_states.set(6)
    # return None


NFA_MOVES_64 = [
    '!',
    '!',
    '%',
    '&',
    '*',
    '+',
    '-',
    '-',
    '/',
    '/',
    '<',
    '?',
    '^',
    '^',
    '|',
    '|'
]

def NFA_FUNCTIONS_DEFAULT_init():
    functions = [
        NfaIndex0,
        NfaIndex1,
        NfaIndex2,
        NfaIndex3,
        NfaIndex4,
        NfaIndex5,
        NfaIndex6,
        NfaIndex7,
        NfaIndex8,
        NfaIndex9,
        NfaIndex10,
        NfaIndex11,
        NfaIndex12,
        NfaIndex13,
        NfaIndex14,
        NfaIndex15,
        NfaIndex16,
        NfaIndex17,
        NfaIndex18,
        NfaIndex19,
        NfaIndex20,
        NfaIndex21,
        NfaIndex22,
        NfaIndex23,
        NfaIndex24,
        NfaIndex25,
        NfaIndex26,
        NfaIndex27,
        NfaIndex28,
        NfaIndex29,
        NfaIndex30,
        NfaIndex31,
        NfaIndex32,
        NfaIndex33,
        NfaIndex34,
        NfaIndex35,
        NfaIndex36,
        NfaIndex37,
        NfaIndex38,
        NfaIndex39,
        NfaIndex40,
        NfaIndex41,
        NfaIndex42,
        NfaIndex43,
        NfaIndex44,
        NfaIndex45,
        NfaIndex46,
        NfaIndex47,
        NfaIndex48
    ]
    return functions

nfa_functions = NFA_FUNCTIONS_DEFAULT_init()


# Just use binary search to check whether the char is in one of the
# intervals
def check_intervals(ranges, ch):
    index = bisect.bisect_left(ranges, ch)
    n = len(ranges)
    if index < n:
        if index % 2 == 0:
            if index < (n - 1):
                return ranges[index] <= ch <= ranges[index + 1]
        elif index > 0:
            return ranges[index - 1] <= ch <= ranges[index]
    return False


# Compute the maximum size of state bitsets

MAX_STATES = 76

# Lexer code and data



def get_function_table_map(lexical_state):
    # We only have one lexical state in this case, so we return that!
    return nfa_functions


CODING_PATTERN = re.compile(rb'^[ \t\f]*#.*coding[:=][ \t]*([-_.a-zA-Z0-9]+)')

def _input_text(input_source):
    # Check if it's an existing filename
    try:
        with open(input_source, 'rb') as f:
            text = f.read()
    except OSError:
        return input_source  # assume it's source rather than a path to source
    implicit = False
    if len(text) <= 3:
        encoding = 'utf-8'
        implicit = True
    elif text[:3] == b'\xEF\xBB\xBF':
        text = text[3:]
        encoding = 'utf-8'
    elif text[:2] == b'\xFF\xFE':
        text = text[2:]
        encoding = 'utf-16le'
    elif text[:2] == b'\xFE\xFF':
        text = text[2:]
        encoding = 'utf-16be'
    elif text[:4] == b'\xFF\xFE\x00\x00':
        text = text[4:]
        encoding = 'utf-32le'
    elif text[:4] == b'\x00\x00\xFE\xFF':
        text = text[4:]
        encoding = 'utf-32be'
    else:
        # No encoding from BOM.
        encoding = 'utf-8'
        implicit = True
        if input_source.endswith(('.py', '.pyw')):
            # Look for coding in first two lines
            parts = text.split(b'\n', 2)
            m = CODING_PATTERN.match(parts[0])
            if not m and len(parts) > 1:
                m = CODING_PATTERN.match(parts[1])
            if m:
                encoding = m.groups()[0].decode('ascii')
    try:
        return text.decode(encoding, errors='replace')
    except UnicodeDecodeError:
        if not implicit:
            raise
        return text.decode('latin-1')

class TokenSource:

    __slots__ = (
        'input_source',
        'tab_size',
        '_skipped',
        '_token_offsets',
        '_token_location_table',
        '_line_offsets',
        '_need_to_calculate_columns',
        'content',
        'content_len',
        'starting_line',
        'starting_column',
    )

    def __init__(
        self, input_source, starting_line, starting_column,
        tab_size, preserve_tabs, preserve_line_endings,
        java_unicode_escape, terminating_string
    ):
        if not input_source:
            raise ValueError('input filename not specified')
        self.input_source = input_source
        text = _input_text(input_source)
        self.tab_size = tab_size
        self.content = self.munge_content(text, preserve_tabs, preserve_line_endings, java_unicode_escape, terminating_string)
        self.content_len = n = len(self.content)
        n += 1
        self._need_to_calculate_columns = BitSet(n)
        self._line_offsets = self.create_line_offsets_table(self.content)
        self._token_location_table = [None] * n
        self._token_offsets = BitSet(n)
        self._skipped = SkippedToken(self, 0, 0)
        self._skipped.is_unparsed = True

    def __len__(self):
        return self.content_len

    def __getitem__(self, i):
        return self.content[i]

    def munge_content(self, content, preserve_tabs, preserve_lines,
                      java_unicode_escape, terminating_string):
        if preserve_tabs and preserve_lines and not java_unicode_escape:
            if terminating_string:
                if content[-len(terminating_string):] != terminating_string:
                    return content
        tab_size = self.tab_size
        buf = []
        index = 0
        # This is just to handle tabs to spaces. If you don't have that setting set, it
        # is really unused.
        col = 0
        # Don't know if this is really needed for Python ...
        code_points = list(content)
        cplen = len(code_points)
        while index < cplen:
            ch = code_points[index]
            index += 1
            if ch == '\n':
                buf.append(ch)
                col = 0
            elif java_unicode_escape and ch == '\\' and index < cplen and code_points[index] == 'u':
                num_preceding_slashes = 0
                i = index - 1
                while i >= 0:
                    if code_points[i] == '\\':
                        num_preceding_slashes += 1
                    else:
                        break
                    i -= 1
                if num_preceding_slashes % 2 == 0:
                    buf.append('\\')
                    col += 1
                    continue
                num_consecutive_us = 0
                i = index
                while i < cplen:
                    if code_points[i] == 'u':
                        num_consecutive_us += 1
                    else:
                        break
                    i += 1
                four_hex_digits = ''.join(code_points[index + num_consecutive_us:index + num_consecutive_us + 4])
                buf.append(chr(int(four_hex_digits, 16)))
                index += num_consecutive_us + 4
                col += 1
            elif not preserve_lines and ch == '\r':
                buf.append('\n')
                col = 0
                if index < cplen and code_points[index] == '\n':
                    index += 1
            elif ch == '\t' and not preserve_tabs:
                spaces_to_add = tab_size - col % tab_size
                for i in range(spaces_to_add):
                    buf.append(' ')
                    col += 1
            else:
                buf.append(ch)
                col += 1
        if terminating_string:
            if content[-len(terminating_string):] != terminating_string:
                buf.append(terminating_string)
        return ''.join(buf)

    def skip_tokens(self, begin, end):
        tlt = self._token_location_table
        for i in range(begin, end):
            tlt[i] = self._skipped

    def cache_token(self, tok):
        begin_offset = tok.begin_offset
        end_offset = tok.end_offset
        toff = self._token_offsets
        toff.set(begin_offset)
        if end_offset > begin_offset + 1:
            # This handles some weird usage cases where token locations
            # have been adjusted.
            toff.clear(begin_offset + 1, end_offset)
        self._token_location_table[begin_offset] = tok

    def uncache_tokens(self, last_token):
        end_offset = last_token.end_offset
        toff = self._token_offsets
        if end_offset < toff.bits:
            toff.clear(last_token.end_offset, toff.bits)

    def next_cached_token(self, offset):
        next_offset = self._token_offsets.next_set_bit(offset)
        return self._token_location_table[next_offset] if next_offset >= 0 else None

    def previous_cached_token(self, offset):
        prev_offset = self._token_offsets.previous_set_bit(offset - 1)
        return self._token_location_table[prev_offset] if prev_offset >= 0 else None

    def get_line_start_offset(self, lineno):
        rln = lineno - self.starting_line
        if rln <= 0:
            return 0
        if rln >= len(self._line_offsets):
            return self.content_len
        return self._line_offsets[rln]

    def get_line_end_offset(self, lineno):
        rln = lineno - self.starting_line
        if rln < 0:
            return 0
        if rln >= len(self._line_offsets):
            return self.content_len
        if rln == len(self._line_offsets) - 1:
            return self.content_len - 1
        return self._line_offsets[rln + 1] - 1

    def get_line_from_offset(self, pos):
        if pos >= self.content_len:
            result = len(self._line_offsets)
            if self.content[-1] != '\n':
                result -= 1
        else:
            sr = bisect.bisect_right(self._line_offsets, pos) - 1
            if sr >= 0:
                result = sr
            else:
                result = sr + 1
        return self.starting_line + result

    def create_line_offsets_table(self, content):
        if not content:
            return [0]
        length = len(content)
        line_count = 0
        length = len(content)
        for i in range(length):
            ch = content[i]
            if ch == '\t':
                self._need_to_calculate_columns.set(line_count)
            if ch == '\n':
                line_count += 1
        if content[-1] != '\n':
            line_count += 1
        result = [0]
        for i in range(length):
            ch = content[i]
            if ch == '\n':
                if (i + 1) == length:
                    break
                result.append(i + 1)
        return result

    def get_codepoint_column_from_offset(self, pos):
        if pos >= self.content_len:
            return 1
        if pos == 0:
            return self.starting_column
        line = self.get_line_from_offset(pos) - self.starting_line
        line_start = self._line_offsets[line]
        start_col_adjustment = 1 if line > 0 else self.starting_column
        unadjusted_col = pos - line_start + start_col_adjustment
        if not self._need_to_calculate_columns[line]:
            return unadjusted_col
        result = start_col_adjustment
        i = line_start
        while i < pos:
            ch = self.content[i]
            if ch == '\t':
                result += self.tab_size - (result - 1) % self.tab_size
            else:
                result += 1
            i += 1
        return result

    def get_line_length(self, lineno):
        soff = self.get_line_start_offset(lineno)
        eoff = self.get_line_end_offset(lineno)
        return eoff - soff + 1

    def get_text(self, start_offset, end_offset):
        return self.content[start_offset:end_offset]

#
# We use a 2-element tuple (matched_type, match_len) instead of the
# MatchInfo class used in the Java code.
#

def _get_match_info(source, pos, active_token_types, nfa_functions,
                    current_states, next_states, match_info):
    source_len = len(source)
    if pos >= source_len:
        return (EOF, 0)
    start = pos
    match_length = 0
    matched_type = INVALID
    already_matched_types = set()
    if current_states is None:
        current_states = BitSet(MAX_STATES)
    else:
        current_states.clear()
    if next_states is None:
        next_states = BitSet(MAX_STATES)
    else:
        next_states.clear()
    # the core NFA loop
    while True:
        # Holder for the new type (if any) matched on this iteration
        if pos <= start:
            current_states.set(0)
        else:
            # What was next_states on the last iteration
            # is now the current_states!
            temp = current_states
            current_states = next_states
            next_states = temp
            next_states.clear()
        if pos >= source_len:
            break
        cur_char = source[pos]
        pos += 1
        next_active = current_states.next_set_bit(0)
        while next_active != -1:
            returned_type = nfa_functions[next_active](cur_char, next_states, active_token_types, already_matched_types)
            # logger.debug('%5d %s %s %s %s', pos, cur_char, returned_type, current_states, next_states)
            if returned_type and (((pos - start) > match_length) or returned_type.value < matched_type.value):
                matched_type = returned_type
                match_length = pos - start
                already_matched_types.add(returned_type)
            next_active = current_states.next_set_bit(next_active + 1)
        if pos >= source_len:
            break
        if next_states.is_empty:
            break
    return (matched_type, match_length)

class Lexer(TokenSource):

    __slots__ = TokenSource.__slots__ + (
        'next_states',
        'current_states',
        'active_token_types',
        'regular_tokens',
        'unparsed_tokens',
        'skipped_tokens',
        'more_tokens',
        'lexical_state',
    )

    def __init__(self, input_source, lex_state=LexicalState.DEFAULT, line=1, column=1):

        super().__init__(
            input_source, line, column, DEFAULT_TAB_SIZE,
            True, True, False, ""
        )
        # The following two BitSets are used to store the current active
        # NFA states in the core tokenization loop
        self.next_states = BitSet(MAX_STATES)
        self.current_states = BitSet(MAX_STATES)

        self.active_token_types = None
        # Just used to "bookmark" the starting location for a token
        # for when we put in the location info at the end.
        self.starting_line = line
        self.starting_column = column

        # Token types that are "regular" tokens that participate in parsing,
        # i.e. declared as TOKEN
        self.regular_tokens = {
            TokenType.EOF,
            TokenType.LEFT_PAREN,
            TokenType.RIGHT_PAREN,
            TokenType.WHITE_SPACE,
            TokenType.COMMENT_SINGLE_LINE,
            TokenType.COMMENT_MULTI_LINE,
            TokenType.INTEGER_LITERAL,
            TokenType.INVALID_LEADING_ZERO_INTEGER,
            TokenType.INVALID_HEX_INTEGER,
            TokenType.FLOATING_POINT_LITERAL,
            TokenType.ANY_LITERAL,
            TokenType.ANY_OPERATOR,
            TokenType.ANY_SEPARATOR,
            TokenType.STRING_LITERAL_DQ,
            TokenType.STRING_LITERAL_SQ
        }

        # Token types that do not participate in parsing
        # i.e. declared as UNPARSED (or SPECIAL_TOKEN)
        self.unparsed_tokens = EMPTY_SET
        self.skipped_tokens = EMPTY_SET
        # Tokens that correspond to a MORE, i.e. that are pending
        # additional input
        self.more_tokens = EMPTY_SET
        self.lexical_state = lex_state
        if lex_state is not None:
            self.switch_to(lex_state)

    #
    # The public method for getting the next token.
    # It checks if we have already cached the token after this one.
    # If not, it goes to the NFA machinery
    #

    def get_next_token(self, tok, active_token_types=None):
        if active_token_types is None:
            active_token_types = self.active_token_types
        if tok is None:
            tok = self._tokenize_at(0, None, active_token_types)
            self.cache_token(tok)
            return tok
        cached_token = tok.next_cached_token
        # If not currently active, discard it and go back to the lexer
        if (cached_token and active_token_types is not None and cached_token.type not in active_token_types):
            self.reset(tok)
            cached_token = None
        if cached_token:
            return cached_token
        tok = self._tokenize_at(tok.end_offset, None, active_token_types)
        self.cache_token(tok)
        return tok

    def _tokenize_at(self, pos, lex_state, active_token_types):
        if lex_state is None:
            lex_state = self.lexical_state
        token_begin_offset = pos
        in_more = False
        invalid_region_start = -1
        matched_token = None
        matched_type = None
        match_info = (None, 0)
        current_states = BitSet(MAX_STATES)
        next_states = BitSet(MAX_STATES)
        # The core tokenization loop
        while matched_token is None:
            if not in_more:
                token_begin_offset = pos
            match_info = _get_match_info(self, pos, active_token_types, nfa_functions, current_states, next_states, match_info)
            matched_type = match_info[0]
            in_more = matched_type in self.more_tokens
            pos += match_info[1]
            if matched_type == INVALID:
                if invalid_region_start == -1:
                    invalid_region_start = token_begin_offset
                # cp = self[pos]
                pos += 1
                continue
            if invalid_region_start != -1:
                return InvalidToken(self, invalid_region_start, token_begin_offset)
            if matched_type in self.skipped_tokens:
                self.skip_tokens(token_begin_offset, pos)
            elif matched_type in self.regular_tokens or matched_type in self.unparsed_tokens:
                matched_token = new_token(matched_type, self, token_begin_offset, pos)
                matched_token.is_unparsed = matched_type not in self.regular_tokens
        return matched_token

    def do_lexical_state_switch(self, token_type):
        new_state = token_type_to_lexical_state_map.get(token_type)
        if new_state is None:
            return False
        return self.switch_to(new_state)

    #
    # Switch to specified lexical state.
    #
    def switch_to(self, lex_state):
        if self.lexical_state != lex_state:
            self.lexical_state = lex_state
            return True
        return False

    # Reset the token source input
    # to just after the Token passed in.
    def reset(self, t, lex_state=None):
        self.uncache_tokens(t)
        if lex_state:
            self.switch_to(lex_state)


    def at_line_start(self, tok):
        offset = tok.begin_offset
        while offset > 0:
            offset -= 1
            c = self.content[offset]
            if not c.isspace():
                return False
            if c == '\n':
                break
        return True

    def get_line(self, tok):
        lineno = tok.begin_line
        soff = self.get_line_start_offset(lineno)
        eoff = self.get_line_end_offset(lineno)
        return self.get_text(soff, eoff + 1)
