# Parser parsing package. Generated by CongoCC Parser Generator. Do not edit.
from enum import Enum, auto, unique
import logging
from .lexer import Lexer
from .tokens import *
from .utils import (EMPTY_SET, ListIterator, StringBuilder, _Set, _List,
make_frozenset, HashSet, HashMap, BitSet)
logger = logging.getLogger(__name__)
#
# Hack to allow token types to be referenced in snippets without
# qualifying
#
globals().update(TokenType.__members__)

class ParseException(Exception):
    def __init__(self, parser, token=None, message=None, expected=None, call_stack=None):
        super().__init__(message)
        self.parser = parser
        if token is None:
            token = parser.last_consumed_token
            if token and token.next:
                token = token.next
        self.token = token
        self.expected = expected
        if call_stack is None:
            call_stack = parser.parsing_stack
        self.call_stack = call_stack[:]

    def __repr__(self):
        if hasattr(self, 'message'):
            return self.message
        parts = []
        if self.token:
            parts.append('unexpected %s (%r) at %s (%d, %d)' %
(self.token.type.name, self.token.image,
self.token.input_source,
self.token.begin_line, self.token.begin_column))
        if self.expected:
            parts.append(', expected %s' % ('' if len(self.expected) == 1 else 'one of '))
            ex = [e.name for e in self.expected]
            parts.append(', '.join(ex))
        return ''.join(parts)

    __str__ = __repr__
def is_lexer(stream_or_lexer):
    return hasattr(stream_or_lexer, 'input_source') and hasattr(stream_or_lexer, 'get_next_token')

UNLIMITED = (1 << 31) - 1

#
# Class that represents entering a grammar production
#
class NonTerminalCall:
    __slots__ = (
'source_file',
'parser',
'production_name',
'line', 'column',
'scan_to_end',
    )
    def __init__(self, parser, filename, prodname, line, column):
        self.parser = parser
        self.source_file = filename
        self.production_name = prodname
        self.line = line
        self.column = column
        # We actually only use this when we're working with the LookaheadStack
        self.scan_to_end = parser.scan_to_end

    def create_stack_trace_element(self):
        return (type(self.parser).__name__, self.production_name, self.source_file, self.line)


class ParseState:
    __slots__ = ('parser', 'last_consumed', 'parsing_stack',
'lexical_state', 'node_scope')
    def __init__(self, parser):
        self.parser = parser
        self.last_consumed = parser.last_consumed_token
        self.parsing_stack = parser.parsing_stack[:]


class InvalidNode(BaseNode):
    pass

class Parser:
    __slots__ = (
'token_source',
'last_consumed_token',
'_next_token_type',
'_dummy_start_token',
'current_lookahead_token',
'remaining_lookahead',
'scan_to_end',
'hit_failure',
'passed_predicate',
'passed_predicate_threshold',
'lookahead_routine_nesting',
'parsing_stack',
'lookahead_stack',
'build_tree',
'tokens_are_nodes',
'unparsed_tokens_are_nodes',
'current_node_scope',
'parse_state_stack',
'tolerant_parsing',
'pending_recovery',
'debug_fault_tolerant',
'parsing_problems',
'currently_parsed_production',
'current_lookahead_production',
    )
    def __init__(self, input_source_or_lexer):
        if not is_lexer(input_source_or_lexer):
            self.token_source = Lexer(input_source_or_lexer)
        else:
            self.token_source = input_source_or_lexer
        self._dummy_start_token = InvalidToken(self.token_source, 0, 0)
        self.last_consumed_token = self._dummy_start_token
        self._next_token_type = None
        self.current_lookahead_token = None
        self.remaining_lookahead = 0
        self.scan_to_end = False
        self.hit_failure = False
        self.passed_predicate = False
        self.passed_predicate_threshold = -1
        self.currently_parsed_production = ''
        self.current_lookahead_production = ''
        self.lookahead_routine_nesting = 0
        self.parsing_stack = []
        self.lookahead_stack = []
        self.parse_state_stack = []

    @property
    def is_tolerant(self):
        return False

    @is_tolerant.setter
    def set_tolerant(self, tolerant):
        if tolerant:
            raise NotImplementedError('This parser was not built with fault tolerance support!')

    @property
    def legacy_glitchy_lookahead(self):
        return False

    @property
    def input_source(self):
        return self.token_source.input_source

    def push_last_token_back(self):
        self.last_consumed_token = self.last_consumed_token.previous_token

    def stash_parse_state(self):
        self.parse_state_stack.append(ParseState(self))

    def pop_parse_state(self):
        return self.parse_state_stack.pop()

    def restore_stashed_parse_state(self):
        state = self.pop_parse_state()
        if state.last_consumed is not None:
        # REVISIT
            self.last_consumed_token = state.last_consumed
        self.token_source.reset(self.last_consumed_token)

    def push_onto_call_stack(self, method_name, filename, line, column):
        self.parsing_stack.append(NonTerminalCall(self, filename, method_name, line, column))

    def pop_call_stack(self):
        ntc = self.parsing_stack.pop()
        self.currently_parsed_production = ntc.production_name

    def restore_call_stack(self, prev_size):
        while len(self.parsing_stack) > prev_size:
            self.pop_call_stack()
            # If the next token is cached, return that
            # Otherwise, go to the lexer

    def next_token(self, tok):
        ts = self.token_source
        result = ts.get_next_token(tok)
        while result.is_unparsed:
            result = ts.get_next_token(result)
        self._next_token_type = None
        return result

    def get_next_token(self):
        return self.get_token(1)

    # If we are in a lookahead, it looks ahead/behind from the current lookahead token
    # Otherwise, it is the last consumed token. If you pass in a negative number, it goes
    # backwards.
    def get_token(self, index):
        t = self.current_lookahead_token or self.last_consumed_token
        if index == 0:
            return t
        elif index > 0:
            for i in range(index):
                t = self.next_token(t)
        else:
            for i in range(-index):
                t = t.previous
                if t is None:
                    break
        return t

    def token_image(self, n):
        return self.get_token(n).image

    def get_token_image(self, n):
        return self.get_token(n).image

    def get_token_type(self, n):
        return self.get_token(n).type

    def check_next_token_image(self, img, *additional_images):
        next_image = self.token_image(1)
        if next_image == img:
            return True
        for ai in additional_images:
            if next_image == ai:
                return True
        return False

    def check_next_token_type(self, tt, *additional_types):
        next_type = self.get_token(1).type
        if next_type == tt:
            return True
        for at in additional_types:
            if next_type == at:
                return True
        return False

    @property
    def next_token_type(self):
        if self._next_token_type is None:
            self._next_token_type = self.next_token(self.last_consumed_token).type
        return self._next_token_type

    def activate_token_types(self, tt, *types):
        result = False
        att = self.token_source.active_token_types
        if tt not in att:
            result = True
            att.add(tt)
        for tt in types:
            if tt not in att:
                result = True
                att.add(tt)
        self.token_source.reset(self.get_token(0))
        self._next_token_type = None
        return result

    def deactivate_token_types(self, tt, *types):
        result = False
        att = self.token_source.active_token_types
        if tt in att:
            result = True
            att.remove(tt)
        for tt in types:
            if tt in att:
                result = True
                att.remove(tt)
        self.token_source.reset(self.get_token(0))
        self._next_token_type = None
        return result

    def uncache_tokens(self):
        self.token_source.reset(self.get_token(0))

    def fail(self, message):
        if self.current_lookahead_token is None:
            raise ParseException(self, message=message)
        self.hit_failure = True

    def is_in_production(self, name, *prods):
        if self.currently_parsed_production is not None:
            if self.currently_parsed_production == name:
                return True
            for prod in prods:
                if self.currently_parsed_production == prod:
                    return True
        if self.current_lookahead_production is not None:
            if self.current_lookahead_production == name:
                return True
            for prod in prods:
                if self.current_lookahead_production == prod:
                    return True
        it = self.stack_iterator_backward()
        while it.has_next:
            ntc = it.next
            npn = ntc.production_name
            if npn == name:
                return True
            for pn in prods:
                if npn == pn:
                    return True
        return False

    # grammar/common/IodxProductions.inc.ccc:4:1
    def parse_parseDocument(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseDocument'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:4:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:5:1
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:8:5
        self.push_onto_call_stack('parseDocument', 'grammar/common/IodxProductions.inc.ccc', 8, 5)
        try:
            document = self.parse_parseListBody()
        finally:
            self.pop_call_stack()
            # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:9:5
        self.consume_token(EOF)
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:10:5
        return document
        # end of parse_parseDocument

    # grammar/common/IodxProductions.inc.ccc:13:1
    def parse_parseListBody(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseListBody'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:13:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:14:1
        start = self.cst_begin_node()
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:18:5
        self.push_onto_call_stack('parseListBody', 'grammar/common/IodxProductions.inc.ccc', 18, 5)
        try:
            list = self.parse_parseList()
        finally:
            self.pop_call_stack()
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:19:5
        return self.cst_list_body(start, list)
        # end of parse_parseListBody

    # grammar/common/IodxProductions.inc.ccc:22:1
    def parse_parseList(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseList'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:22:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:23:1
        list = self.cst_new_list()
        # Code for ZeroOrOne specified at grammar/common/IodxProductions.inc.ccc:27:5
        if (self.type_matches(WHITE_SPACE, self.get_token(1))) :
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:27:7
            self.consume_token(WHITE_SPACE)
            # Code for ZeroOrOne specified at grammar/common/IodxProductions.inc.ccc:28:5
        if (self.has_match(self.first_setΣIodxProductions_inc_cccΣ29Σ7,self.get_token(1))) :
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:29:7
            self.push_onto_call_stack('parseList', 'grammar/common/IodxProductions.inc.ccc', 29, 7)
            try:
                value = self.parse_parseElement()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:29:28
            self.cst_list_add(list, value)
            # Code for ZeroOrOne specified at grammar/common/IodxProductions.inc.ccc:30:7
            if (self.type_matches(WHITE_SPACE, self.get_token(1))) :
            # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:30:9
                self.consume_token(WHITE_SPACE)
                # Code for ZeroOrMore specified at grammar/common/IodxProductions.inc.ccc:31:7
            while True:
                if not ((self.has_match(self.first_setΣIodxProductions_inc_cccΣ32Σ9,self.get_token(1))) ): break
                # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:32:9
                self.push_onto_call_stack('parseList', 'grammar/common/IodxProductions.inc.ccc', 32, 9)
                try:
                    value = self.parse_parseElement()
                finally:
                    self.pop_call_stack()
                    # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:32:30
                self.cst_list_add(list, value)
                # Code for ZeroOrOne specified at grammar/common/IodxProductions.inc.ccc:33:9
                if (self.type_matches(WHITE_SPACE, self.get_token(1))) :
                # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:33:11
                    self.consume_token(WHITE_SPACE)
                    # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:36:5
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:36:5
        return list
        # end of parse_parseList

    # grammar/common/IodxProductions.inc.ccc:39:1
    def parse_parseElement(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseElement'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:39:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:40:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:45:5
        token = None
        node = None
        if ((self.type_matches(ANY_LITERAL, self.get_token(1))) ):
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:47:7
            self.push_onto_call_stack('parseElement', 'grammar/common/IodxProductions.inc.ccc', 47, 7)
            try:
                node = self.parse_parseIdentifierOrClass()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:47:37
            return node
        elif ((self.type_matches(LEFT_PAREN, self.get_token(1))) ):
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:49:7
            self.push_onto_call_stack('parseElement', 'grammar/common/IodxProductions.inc.ccc', 49, 7)
            try:
                node = self.parse_parseUnnamedClass()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:49:32
            return node
        elif ((self.type_matches(COMMENT_SINGLE_LINE, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:51:7
            token = self.consume_token(COMMENT_SINGLE_LINE)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:51:37
            return self.cst_single_line_comment(token)
        elif ((self.type_matches(COMMENT_MULTI_LINE, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:53:7
            token = self.consume_token(COMMENT_MULTI_LINE)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:53:36
            return self.cst_multi_line_comment(token)
        elif ((self.type_matches(INTEGER_LITERAL, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:55:7
            token = self.consume_token(INTEGER_LITERAL)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:55:33
            return self.cst_integer(token)
        elif ((self.type_matches(FLOATING_POINT_LITERAL, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:57:7
            token = self.consume_token(FLOATING_POINT_LITERAL)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:57:40
            return self.cst_floating_point(token)
        elif ((self.type_matches(ANY_OPERATOR, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:59:7
            token = self.consume_token(ANY_OPERATOR)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:59:30
            return self.cst_raw_token("ANY_OPERATOR", token)
        elif ((self.type_matches(ANY_SEPARATOR, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:61:7
            token = self.consume_token(ANY_SEPARATOR)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:61:31
            return self.cst_raw_token("ANY_SEPARATOR", token)
        elif ((self.type_matches(STRING_LITERAL_DQ, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:63:7
            token = self.consume_token(STRING_LITERAL_DQ)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:63:35
            return self.cst_string("STRING_LITERAL_DQ", token)
        elif ((self.type_matches(STRING_LITERAL_SQ, self.get_token(1))) ):
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:65:7
            token = self.consume_token(STRING_LITERAL_SQ)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:65:35
            return self.cst_string("STRING_LITERAL_SQ", token)
        else: # not *, +, or ?

            self.push_onto_call_stack('parseElement', 'grammar/common/IodxProductions.inc.ccc', 47, 7)
            raise ParseException(self, expected=self.first_setΣIodxProductions_inc_cccΣ47Σ7)
            # end of parse_parseElement

    # grammar/common/IodxProductions.inc.ccc:70:1
    def parse_parseIdentifierOrClass(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseIdentifierOrClass'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:70:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:71:1
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:78:5
        identifier = self.consume_token(ANY_LITERAL)
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:78:32
        name_node = self.cst_identifier(identifier)
        # Code for ZeroOrOne specified at grammar/common/IodxProductions.inc.ccc:79:5
        if (self.type_matches(LEFT_PAREN, self.get_token(1))) :
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:80:9
            self.push_onto_call_stack('parseIdentifierOrClass', 'grammar/common/IodxProductions.inc.ccc', 80, 9)
            try:
                left_paren_node = self.parse_parseLeftParen()
            finally:
                self.pop_call_stack()
                # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:81:9
            self.push_onto_call_stack('parseIdentifierOrClass', 'grammar/common/IodxProductions.inc.ccc', 81, 9)
            try:
                body = self.parse_parseListBody()
            finally:
                self.pop_call_stack()
                # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:82:9
            self.push_onto_call_stack('parseIdentifierOrClass', 'grammar/common/IodxProductions.inc.ccc', 82, 9)
            try:
                right_paren_node = self.parse_parseRightParen()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:83:9
            return self.cst_class(name_node, left_paren_node, body, right_paren_node)
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:85:5
        return name_node
        # end of parse_parseIdentifierOrClass

    # grammar/common/IodxProductions.inc.ccc:88:1
    def parse_parseLeftParen(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseLeftParen'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:88:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:89:1
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:92:5
        token = self.consume_token(LEFT_PAREN)
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:92:26
        return self.cst_structural_token("LEFT_PAREN", token)
        # end of parse_parseLeftParen

    # grammar/common/IodxProductions.inc.ccc:95:1
    def parse_parseRightParen(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseRightParen'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:95:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:96:1
        # Code for Terminal specified at grammar/common/IodxProductions.inc.ccc:99:5
        token = self.consume_token(RIGHT_PAREN)
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:99:27
        return self.cst_structural_token("RIGHT_PAREN", token)
        # end of parse_parseRightParen

    # grammar/common/IodxProductions.inc.ccc:103:1
    def parse_parseUnnamedClass(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseUnnamedClass'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:103:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:104:1
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:109:5
        self.push_onto_call_stack('parseUnnamedClass', 'grammar/common/IodxProductions.inc.ccc', 109, 5)
        try:
            left_paren_node = self.parse_parseLeftParen()
        finally:
            self.pop_call_stack()
            # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:110:5
        self.push_onto_call_stack('parseUnnamedClass', 'grammar/common/IodxProductions.inc.ccc', 110, 5)
        try:
            body = self.parse_parseListBody()
        finally:
            self.pop_call_stack()
            # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:111:5
        self.push_onto_call_stack('parseUnnamedClass', 'grammar/common/IodxProductions.inc.ccc', 111, 5)
        try:
            right_paren_node = self.parse_parseRightParen()
        finally:
            self.pop_call_stack()
            # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:112:5
        return self.cst_class(None, left_paren_node, body, right_paren_node)
        # end of parse_parseUnnamedClass

    # grammar/common/IodxProductions.inc.ccc:116:1
    def parse_parseClass(self, ):
    # import pdb; pdb.set_trace()
        self.currently_parsed_production = 'parseClass'
        # Code for BNFProduction specified at grammar/common/IodxProductions.inc.ccc:116:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:117:1
        # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:121:5
        node = None
        if ((self.type_matches(ANY_LITERAL, self.get_token(1))) ):
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:123:7
            self.push_onto_call_stack('parseClass', 'grammar/common/IodxProductions.inc.ccc', 123, 7)
            try:
                node = self.parse_parseIdentifierOrClass()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:123:37
            return self.cst_require_class(node)
        elif ((self.type_matches(LEFT_PAREN, self.get_token(1))) ):
        # Code for NonTerminal specified at grammar/common/IodxProductions.inc.ccc:125:7
            self.push_onto_call_stack('parseClass', 'grammar/common/IodxProductions.inc.ccc', 125, 7)
            try:
                node = self.parse_parseUnnamedClass()
            finally:
                self.pop_call_stack()
                # Code for CodeBlock specified at grammar/common/IodxProductions.inc.ccc:125:32
            return node
        else: # not *, +, or ?

            self.push_onto_call_stack('parseClass', 'grammar/common/IodxProductions.inc.ccc', 123, 7)
            raise ParseException(self, expected=self.first_setΣIodxProductions_inc_cccΣ123Σ7)
            # end of parse_parseClass
            # ==================================================================
            # EnumSets that represent the various expansions' first set (i.e. the set of tokens with which the expansion can begin)
            # ==================================================================

    first_setΣIodxProductions_inc_cccΣ29Σ7 = make_frozenset(
LEFT_PAREN,
COMMENT_SINGLE_LINE,
COMMENT_MULTI_LINE,
INTEGER_LITERAL,
FLOATING_POINT_LITERAL,
ANY_LITERAL,
ANY_OPERATOR,
ANY_SEPARATOR,
STRING_LITERAL_DQ,
STRING_LITERAL_SQ
    )
    first_setΣIodxProductions_inc_cccΣ32Σ9 = make_frozenset(
LEFT_PAREN,
COMMENT_SINGLE_LINE,
COMMENT_MULTI_LINE,
INTEGER_LITERAL,
FLOATING_POINT_LITERAL,
ANY_LITERAL,
ANY_OPERATOR,
ANY_SEPARATOR,
STRING_LITERAL_DQ,
STRING_LITERAL_SQ
    )
    first_setΣIodxProductions_inc_cccΣ47Σ7 = make_frozenset(
LEFT_PAREN,
COMMENT_SINGLE_LINE,
COMMENT_MULTI_LINE,
INTEGER_LITERAL,
FLOATING_POINT_LITERAL,
ANY_LITERAL,
ANY_OPERATOR,
ANY_SEPARATOR,
STRING_LITERAL_DQ,
STRING_LITERAL_SQ
    )
    first_setΣIodxProductions_inc_cccΣ123Σ7 = make_frozenset(
LEFT_PAREN,
ANY_LITERAL
    )
    def scan_token_one(self, expected_type):
        peeked_token = self.next_token(self.current_lookahead_token)
        if not self.type_matches(expected_type, peeked_token):
            return False
        self.remaining_lookahead -= 1
        self.current_lookahead_token = peeked_token
        return True

    def scan_token_many(self, expected_types):
        peeked_token = self.next_token(self.current_lookahead_token)
        if not self.has_match(expected_types, peeked_token):
            return False
        self.remaining_lookahead -= 1
        self.current_lookahead_token = peeked_token
        return True

    pass
    def type_matches(self, type, tok) :
        return tok.type == type

    def has_match(self, types, tok) :
        return tok.type in types

    def stack_iterator_forward(self):

        class ForwardIterator:
            def __init__(self, iter1, iter2):
                self.iter1 = ListIterator(iter1)
                self.iter2 = ListIterator(iter2)

            @property
            def has_next(self):
                return self.iter1.has_next or self.iter2.has_next

            @property
            def next(self):
                return self.iter1.next if self.iter1.has_next else self.iter2.next

            @property
            def has_previous(self):
                return self.iter2.has_previous or self.iter1.has_previous

            @property
            def previous(self):
                return self.iter2.previous if self.iter2.has_previous else self.iter1.previous

        return ForwardIterator(self.parsing_stack, self.lookahead_stack)

    def stack_iterator_backward(self):

        class BackwardIterator:
            def __init__(self, iter1, iter2):
                self.iter1 = ListIterator(iter1, len(iter1))
                self.iter2 = ListIterator(iter2, len(iter2))

            @property
            def has_next(self):
                return self.iter2.has_previous or self.iter1.has_previous

            @property
            def next(self):
                return self.iter2.previous if self.iter2.has_previous else self.iter1.previous

            @property
            def has_previous(self):
                return self.iter1.has_next or self.iter2.has_next

            @property
            def previous(self):
                return self.iter1.next if self.iter1.has_next else self.iter2.next

        return BackwardIterator(self.parsing_stack, self.lookahead_stack)

    def push_onto_lookahead_stack(self, method_name, filename, line, column):
        self.lookahead_stack.append(NonTerminalCall(self, filename, method_name, line, column))

    def pop_lookahead_stack(self):
        ntc = self.lookahead_stack.pop()
        self.current_lookahead_production = ntc.production_name
        self.scan_to_end = ntc.scan_to_end

    def consume_token(self, expected_type):
    # old_token = self.last_consumed_token
        next_token = self.next_token(self.last_consumed_token)
        if not self.type_matches(expected_type,next_token) :
            next_token = self.handle_unexpected_token_type(expected_type, next_token)
        self.last_consumed_token = next_token
        self._next_token_type = None
        return self.last_consumed_token

    def handle_unexpected_token_type(self, expected_type, next_token):
        raise ParseException(self, token=next_token, expected=set([expected_type]))

    @property
    def is_tree_building_enabled(self):
        return False

    def cst_begin_node(self):
        token = self.get_token(0)
        start = HashMap()
        start.put("beginLine", token.begin_line)
        start.put("beginColumn", token.begin_column)
        start.put("beginOffset", token.begin_offset)
        return start

    def cst_new_list(self):
        return _List()

    def cst_list_add(self, list, value):
        list.add(value)

    def cst_list_body(self, start, children):
        end = self.get_token(0)
        return self.cst_ranged_node("LIST_BODY", start, end, None, children, HashMap())

    def cst_single_line_comment(self, token):
        return self.cst_token_node("COMMENT_SINGLE_LINE", token, str(token))

    def cst_multi_line_comment(self, token):
        return self.cst_token_node("COMMENT_MULTI_LINE", token, str(token))

    def cst_integer(self, token):
        return self.cst_token_node("INTEGER_LITERAL", token, str(token))

    def cst_floating_point(self, token):
        return self.cst_token_node("FLOATING_POINT_LITERAL", token, str(token))

    def cst_raw_token(self, type, token):
        return self.cst_token_node(type, token, str(token))

    def cst_structural_token(self, type, token):
        return self.cst_token_node(type, token, None)

    def cst_string(self, type, token):
        return self.cst_token_node(type, token, str(token))

    def cst_identifier(self, token):
        return self.cst_token_node("ANY_LITERAL", token, str(token))

    def cst_class(self, name, left, body, right):
        start = (left if (name is None) else name)
        children = _List()
        fields = HashMap()
        if (name is not None):
            fields.put("name", name)
            children.add(name)
        children.add(left)
        children.add(body)
        children.add(right)
        fields.put("body", body)
        return self.cst_node(("UNNAMED_CLASS" if (name is None) else "NAMED_CLASS"), start["beginLine"], start["beginColumn"], right["endLine"], right["endColumn"], start["beginOffset"], right["endOffset"], None, children, fields)

    def cst_require_class(self, node):
        if node["type"] == "NAMED_CLASS":
            return node
        raise ParseException(self, self.get_token(0), ("Expected a class, but got: " + node["type"]))

    def cst_token_node(self, type, token, value):
        return self.cst_node(type, token.begin_line, token.begin_column, token.end_line, token.end_column, token.begin_offset, token.end_offset, value, _List(), HashMap())

    def cst_ranged_node(self, type, start, end, value, children, fields):
        return self.cst_node(type, start["beginLine"], start["beginColumn"], end.end_line, end.end_column, start["beginOffset"], end.end_offset, value, children, fields)

    def cst_node(self, type, begin_line, begin_column, end_line, end_column, begin_offset, end_offset, value, children, fields):
        node = HashMap()
        node.put("type", type)
        node.put("beginLine", begin_line)
        node.put("beginColumn", begin_column)
        node.put("endLine", end_line)
        node.put("endColumn", end_column)
        node.put("beginOffset", begin_offset)
        node.put("endOffset", end_offset)
        node.put("value", value)
        node.put("children", children)
        node.put("fields", fields)
        return node
