# Parser tokens package. Generated by CongoCC Parser Generator. Do not edit.

from enum import Enum, auto, unique

from .utils import _GenWrapper, _List

__all__ = [
    'BaseNode',
    'TokenType',
    'Token',
    'INVALID_HEX_INTEGER',
    'COMMENT_MULTI_LINE',
    'FLOATING_POINT_LITERAL',
    'STRING_LITERAL_DQ',
    'RIGHT_PAREN',
    'INTEGER_LITERAL',
    'ANY_LITERAL',
    'LEFT_PAREN',
    'ANY_OPERATOR',
    'STRING_LITERAL_SQ',
    'INVALID_LEADING_ZERO_INTEGER',
    'WHITE_SPACE',
    'COMMENT_SINGLE_LINE',
    'ANY_SEPARATOR',
    'new_token',
    'InvalidToken',
    'IgnoredToken',
    'SkippedToken',
    'LexicalState'
]

@unique
class TokenType(Enum):
    EOF = auto()
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    WHITE_SPACE = auto()
    COMMENT_SINGLE_LINE = auto()
    COMMENT_MULTI_LINE = auto()
    INTEGER_LITERAL = auto()
    INVALID_LEADING_ZERO_INTEGER = auto()
    INVALID_HEX_INTEGER = auto()
    FLOATING_POINT_LITERAL = auto()
    ANY_LITERAL = auto()
    ANY_OPERATOR = auto()
    ANY_SEPARATOR = auto()
    STRING_LITERAL_DQ = auto()
    STRING_LITERAL_SQ = auto()
    INVALID = auto()

@unique
class LexicalState(Enum):
    DEFAULT = auto()

class BaseNode:

    __slots__ = (
        '_token_source',
        'parent',
        'children',
        'is_unparsed',
        'begin_offset',
        'end_offset',
        'named_child_map',
        'named_child_list_map',
    )

    def __init__(self, token_source, begin_offset=0, end_offset=0):
        self._token_source = token_source
        self.parent = None
        self.children = []
        self.begin_offset = begin_offset
        self.end_offset = end_offset
        self.named_child_map = {}
        self.named_child_list_map = {}
        # self.attributes = {}

    @property
    def begin_line(self):
        ts = self.token_source
        return 0 if not ts else ts.get_line_from_offset(self.begin_offset)

    @property
    def begin_column(self):
        ts = self.token_source
        return 0 if not ts else ts.get_codepoint_column_from_offset(self.begin_offset)

    @property
    def end_line(self):
        if self.end_offset <= self.begin_offset: return self.begin_line
        ts = self.token_source
        return 0 if not ts else ts.get_line_from_offset(self.end_offset - 1)

    @property
    def end_column(self):
        if self.end_offset <= self.begin_offset: return self.begin_column
        ts = self.token_source
        return 0 if not ts else ts.get_codepoint_column_from_offset(self.end_offset - 1)

    @property
    def token_source(self):
        result = self._token_source
        return result

    @token_source.setter
    def token_source(self, value):
        self._token_source = value

    @property
    def input_source(self):
        ts = self.token_source
        return "input" if not ts else ts.input_source

    def add(self, node, index=-1):
        if index < 0:
            self.children.append(node)
        else:
            self.children.insert(index, node)
        node.parent = self

    def remove(self, index):
        assert index >= 0
        self.children.pop(index)

    def __delitem__(self, index):
        n = len(self.children)
        if index < 0:
            index = n - index
        assert 0 <= index < n
        self.remove(index)

    def truncate(self, amount):
        new_end_offset = max(self.begin_offset, self.end_offset - amount)
        self.end_offset = new_end_offset

    def set_child(self, node, index):
        self.children[index] = node
        node.parent = self

    def __setitem__(self, index, node):
        n = len(self.children)
        if index < 0:
            index = n - index
        assert 0 <= index < n
        self.set_child(node, index)

    def clear_children(self):
        self.children.clear()

    @property
    def child_count(self):
        return len(self.children)

    def get_child(self, index):
        assert index >= 0
        return self.children[index]

    def __getitem__(self, index):
        n = len(self.children)
        if index < 0:
            index = n - index
        assert 0 <= index < n
        return self.get_child(index)

    @property
    def first_child(self):
        if self.children:
            return self.children[0]

    @property
    def last_child(self):
        if self.children:
            return self.children[-1]

    # Copy the location info from another node or start/end nodes
    def copy_location_info(self, start, end=None):
        self.token_source = start.token_source
        self.begin_offset = start.begin_offset
        if end is None:
            self.end_offset = start.end_offset
        if end is not None:
            if self.token_source is None:
                self.token_source = end.token_source
            self.end_offset = end.end_offset

    def open(self): pass

    def close(self): pass

    @property
    def token_type(self):
        if isinstance(self, Token):
            return self.type
        # return None

    #
    # Return the very first token that is part of this node.
    # It may be an unparsed (i.e. special) token.
    #
    @property
    def first_token(self):
        first = self.first_child
        if first is None:
            return None
        if isinstance(first, Token):
            tok = first
            while tok.previous_token is not None and tok.previous_token.is_unparsed:
                tok = tok.previous_token
            return tok
        return first.first_token

    @property
    def last_token(self):
        last = self.last_child
        if last is None:
            return None
        if isinstance(last, Token):
            return last
        return last.last_token


    def children_of_type(self, cls):
        return [child for child in self.children if isinstance(child, cls)]

    def first_child_of_type(self, type):
        for child in self.children:
            if isinstance(child, Token) and child.type == type:
                return child

    def has_child_of_type(self, type) :
        return first_child_of_type(self, type) != None

    def first_descendant_of_type(self, type):
        for child in self.children:
            if isinstance(child, Token):
                if child.type == type:
                    return child
            child = child.first_descendant_of_type(type)
            if child:
                return child

    def descendants(self, cls=None, predicate=None):
        if cls is None:
            cls = BaseNode
        result = []
        for child in self.children:
            if isinstance(child, cls):
                if not predicate or predicate(child):
                    result.append(child)
        return result

    @property
    def real_tokens(self):
        return self.descendants(Token, lambda t: not t.is_unparsed)


    def get_named_child(self, name):
        return self.named_child_map.get(name)

    def set_named_child(self, name, child):
        if name in self.named_child_map:
            raise ValueError('Duplicate named child not allowed: %s' % name)
        self.named_child_map[name] = child

    def get_named_child_list(self, name):
        return self.named_child_list_map.get(name)

    def add_to_named_child_list(self, name, child):
        existing = self.named_child_list_map.setdefault(name, [])
        existing.append(child)

    def __repr__(self):
        return '<%s (%d, %d)-(%d, %d)>' % (type(self).__name__,
                                           self.begin_line,
                                           self.begin_column,
                                           self.end_line,
                                           self.end_column)

class Token:

    __slots__ = (
        'type',
        'previous_token',
        'next_token',
        'begin_offset',
        'end_offset',
        'is_unparsed',
        'token_source',
    )

    def __init__(self, type, token_source, begin_offset, end_offset):
        self.begin_offset = begin_offset
        self.end_offset = end_offset
        self.token_source = token_source

        self.type = type
        self.previous_token = None
        self.next_token = None
        self.is_unparsed = False

    def replace_type(self, tt):
        result = new_token(tt, self.token_source, self.begin_offset, self.end_offset)
        self.token_source.cache_token(result)
        return result

    @property
    def image(self):
        return self.source

    @property
    def source(self):
        if self.type == TokenType.EOF:
            return ''
        ts = self.token_source
        return None if not ts else ts.get_text(self.begin_offset, self.end_offset)

    @property
    def source_line(self):
        ts = self.token_source
        return None if not ts else ts.get_line(self)


    def __str__(self):
        return self.image

    def _preceding_tokens(self):
        current = self
        t = current.previous_cached_token
        while t:
            current = t
            t = current.previous_cached_token
            yield current

    def preceding_tokens(self):
        return _GenWrapper(self._preceding_tokens())

    def _following_tokens(self):
        current = self
        t = current.next_cached_token
        while t:
            current = t
            t = current.next_cached_token
            yield current

    def following_tokens(self):
        return _GenWrapper(self._following_tokens())

    @property
    def is_virtual(self):
        return self.type == TokenType.EOF

    @property
    def is_skipped(self):
        return False

    def _get_next(self):
        return self.get_next_parsed_token()

    def _set_next(self, next):  # This is typically only used internally
        self.set_next_parsed_token(next)

    next = property(_get_next, _set_next)

    # return the next regular (i.e. parsed) token
    def get_next_parsed_token(self):
        result = self.next_cached_token
        while result and result.is_unparsed:
            result = result.next_cached_token
        return result

    @property
    def previous(self):
        result = self.previous_cached_token
        while result and result.is_unparsed:
            result = result.previous_cached_token
        return result

    @property
    def previous_cached_token(self):
        ts = self.token_source
        if not ts:
            return None
        return ts.previous_cached_token(self.begin_offset)

    @property
    def next_cached_token(self):
        ts = self.token_source
        if not ts:
            return None
        return ts.next_cached_token(self.end_offset)

    def __repr__(self):
        tn = self.type.name if self.type else None
        return '<%s %s %r (%d, %d)-(%d, %d)>' % (type(self).__name__,
                                                 tn,
                                                 self.image,
                                                 self.begin_line,
                                                 self.begin_column,
                                                 self.end_line,
                                                 self.end_column)

    # Copy the location info from another token or start/end tokens
    def copy_location_info(self, start, end=None):
        self.token_source = start.token_source
        self.begin_offset = start.begin_offset
        if end is None:
            self.end_offset = start.end_offset
        else:
            if self.token_source is None:
                self.token_source = end.token_source
            self.end_offset = end.end_offset

    @property
    def input_source(self):
        ts = self.token_source
        return 'input' if ts is None else ts.input_source

    @property
    def location(self):
        return '%s:%s:%s' % (self.input_source, self.begin_line,
                             self.begin_column)

    @property
    def begin_line(self):
        ts = self.token_source
        return 0 if not ts else ts.get_line_from_offset(self.begin_offset)

    @property
    def begin_column(self):
        ts = self.token_source
        return 0 if not ts else ts.get_codepoint_column_from_offset(self.begin_offset)

    @property
    def end_line(self):
        if self.end_offset <= self.begin_offset: return self.begin_line
        ts = self.token_source
        return 0 if not ts else ts.get_line_from_offset(self.end_offset - 1)

    @property
    def end_column(self):
        if self.end_offset <= self.begin_offset: return self.begin_column
        ts = self.token_source
        return 0 if not ts else ts.get_codepoint_column_from_offset(self.end_offset - 1)




class InvalidToken(Token):
    def __init__(self, token_source, begin_offset, end_offset):
        super().__init__(TokenType.INVALID, token_source, begin_offset, end_offset)

class IgnoredToken(InvalidToken): pass
class SkippedToken(InvalidToken): pass

#
# Token subclasses
#
class INVALID_HEX_INTEGER(Token): pass

class COMMENT_MULTI_LINE(Token): pass

class FLOATING_POINT_LITERAL(Token): pass

class STRING_LITERAL_DQ(Token): pass

class RIGHT_PAREN(Token): pass

class INTEGER_LITERAL(Token): pass

class ANY_LITERAL(Token): pass

class LEFT_PAREN(Token): pass

class ANY_OPERATOR(Token): pass

class STRING_LITERAL_SQ(Token): pass

class INVALID_LEADING_ZERO_INTEGER(Token): pass

class WHITE_SPACE(Token): pass

class COMMENT_SINGLE_LINE(Token): pass

class ANY_SEPARATOR(Token): pass


def new_token(type, token_source, begin_offset, end_offset):
    return Token(type, token_source, begin_offset, end_offset)
